/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_viennacl_binding_Matrix */

#ifndef _Included_org_viennacl_binding_Matrix
#define _Included_org_viennacl_binding_Matrix
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
