/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_opencl_util_FloatMergeSort */

#ifndef _Included_org_moa_opencl_util_FloatMergeSort
#define _Included_org_moa_opencl_util_FloatMergeSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_opencl_util_FloatMergeSort
 * Method:    init
 * Signature: (Lorg/viennacl/binding/Context;)V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_util_FloatMergeSort_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_moa_opencl_util_FloatMergeSort
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_util_FloatMergeSort_release
  (JNIEnv *, jobject);

/*
 * Class:     org_moa_opencl_util_FloatMergeSort
 * Method:    nativeSort
 * Signature: (Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_util_FloatMergeSort_nativeSort
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
