/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_opencl_sgd_MultinominalLogistic */

#ifndef _Included_org_moa_opencl_sgd_MultinominalLogistic
#define _Included_org_moa_opencl_sgd_MultinominalLogistic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_opencl_sgd_MultinominalLogistic
 * Method:    computeTempMargins
 * Signature: (Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;IIIIILorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_sgd_MultinominalLogistic_computeTempMargins
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
