/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_opencl_util_CLogsSort */

#ifndef _Included_org_moa_opencl_util_CLogsSort
#define _Included_org_moa_opencl_util_CLogsSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_opencl_util_CLogsSort
 * Method:    nativeSort
 * Signature: (Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_util_CLogsSort_nativeSort
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint);

/*
 * Class:     org_moa_opencl_util_CLogsSort
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_util_CLogsSort_release
  (JNIEnv *, jobject);

/*
 * Class:     org_moa_opencl_util_CLogsSort
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_util_CLogsSort_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
