/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_viennacl_binding_Kernel */

#ifndef _Included_org_viennacl_binding_Kernel
#define _Included_org_viennacl_binding_Kernel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_viennacl_binding_Kernel
 * Method:    set_local_size
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_viennacl_binding_Kernel_set_1local_1size
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_viennacl_binding_Kernel
 * Method:    set_global_size
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_viennacl_binding_Kernel_set_1global_1size
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_viennacl_binding_Kernel
 * Method:    set_arg
 * Signature: (ILorg/viennacl/binding/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_viennacl_binding_Kernel_set_1arg__ILorg_viennacl_binding_Buffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_viennacl_binding_Kernel
 * Method:    set_arg
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_viennacl_binding_Kernel_set_1arg__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_viennacl_binding_Kernel
 * Method:    set_arg
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_viennacl_binding_Kernel_set_1arg__IJ
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     org_viennacl_binding_Kernel
 * Method:    invoke
 * Signature: ([Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_viennacl_binding_Kernel_invoke___3Ljava_lang_Object_2
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_viennacl_binding_Kernel
 * Method:    invoke
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_viennacl_binding_Kernel_invoke__
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
