/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_gpu_FJLT */

#ifndef _Included_org_moa_gpu_FJLT
#define _Included_org_moa_gpu_FJLT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_gpu_FJLT
 * Method:    native_transform
 * Signature: (Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;ILorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_FJLT_native_1transform
  (JNIEnv *, jobject, jobject, jobject, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
