/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_opencl_util_Operations */

#ifndef _Included_org_moa_opencl_util_Operations
#define _Included_org_moa_opencl_util_Operations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_opencl_util_Operations
 * Method:    dense_ax
 * Signature: (Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_util_Operations_dense_1ax
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
