/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_viennacl_binding_Operations */

#ifndef _Included_org_viennacl_binding_Operations
#define _Included_org_viennacl_binding_Operations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_viennacl_binding_Operations
 * Method:    Multiply
 * Signature: (Lorg/viennacl/binding/Matrix;Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_viennacl_binding_Operations_Multiply
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
