/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_opencl_util_MortonCode */

#ifndef _Included_org_moa_opencl_util_MortonCode
#define _Included_org_moa_opencl_util_MortonCode
#ifdef __cplusplus
extern "C" {
#endif
#undef org_moa_opencl_util_MortonCode_BYTE_COUNT
#define org_moa_opencl_util_MortonCode_BYTE_COUNT 256L
/*
 * Class:     org_moa_opencl_util_MortonCode
 * Method:    init
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_util_MortonCode_init
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
