/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_viennacl_binding_Queue */

#ifndef _Included_org_viennacl_binding_Queue
#define _Included_org_viennacl_binding_Queue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_viennacl_binding_Queue
 * Method:    flush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_viennacl_binding_Queue_flush
  (JNIEnv *, jobject);

/*
 * Class:     org_viennacl_binding_Queue
 * Method:    finish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_viennacl_binding_Queue_finish
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
