/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_opencl_sgd_DirectUpdater */

#ifndef _Included_org_moa_opencl_sgd_DirectUpdater
#define _Included_org_moa_opencl_sgd_DirectUpdater
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_opencl_sgd_DirectUpdater
 * Method:    nativeAtomicUpdate
 * Signature: (JJID)V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_sgd_DirectUpdater_nativeAtomicUpdate
  (JNIEnv *, jobject, jlong, jlong, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
