/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_opencl_util_DoubleMergeSort */

#ifndef _Included_org_moa_opencl_util_DoubleMergeSort
#define _Included_org_moa_opencl_util_DoubleMergeSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_opencl_util_DoubleMergeSort
 * Method:    init
 * Signature: (Lorg/viennacl/binding/Context;)V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_util_DoubleMergeSort_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_moa_opencl_util_DoubleMergeSort
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_util_DoubleMergeSort_release
  (JNIEnv *, jobject);

/*
 * Class:     org_moa_opencl_util_DoubleMergeSort
 * Method:    nativeSort
 * Signature: (Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_util_DoubleMergeSort_nativeSort
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
