/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_viennacl_binding_MappedFile */

#ifndef _Included_org_viennacl_binding_MappedFile
#define _Included_org_viennacl_binding_MappedFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_viennacl_binding_MappedFile
 * Method:    nativeAttach
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_viennacl_binding_MappedFile_nativeAttach
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     org_viennacl_binding_MappedFile
 * Method:    nativeDetach
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_viennacl_binding_MappedFile_nativeDetach
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
