/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_viennacl_binding_DoubleVector */

#ifndef _Included_org_viennacl_binding_DoubleVector
#define _Included_org_viennacl_binding_DoubleVector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_viennacl_binding_DoubleVector
 * Method:    allocate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_viennacl_binding_DoubleVector_allocate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_viennacl_binding_DoubleVector
 * Method:    commit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_viennacl_binding_DoubleVector_commit
  (JNIEnv *, jobject);

/*
 * Class:     org_viennacl_binding_DoubleVector
 * Method:    init
 * Signature: (Lorg/viennacl/binding/Context;I)V
 */
JNIEXPORT void JNICALL Java_org_viennacl_binding_DoubleVector_init
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
