/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_gpu_MatrixRandomProjection */

#ifndef _Included_org_moa_gpu_MatrixRandomProjection
#define _Included_org_moa_gpu_MatrixRandomProjection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_gpu_MatrixRandomProjection
 * Method:    project
 * Signature: (Lorg/viennacl/binding/Buffer;ILorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_MatrixRandomProjection_project__Lorg_viennacl_binding_Buffer_2ILorg_viennacl_binding_Buffer_2Lorg_viennacl_binding_Buffer_2II
  (JNIEnv *, jobject, jobject, jint, jobject, jobject, jint, jint);

/*
 * Class:     org_moa_gpu_MatrixRandomProjection
 * Method:    project
 * Signature: (Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_MatrixRandomProjection_project__Lorg_viennacl_binding_Buffer_2Lorg_viennacl_binding_Buffer_2Lorg_viennacl_binding_Buffer_2II
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
