/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_opencl_sgd_Multinominal */

#ifndef _Included_org_moa_opencl_sgd_Multinominal
#define _Included_org_moa_opencl_sgd_Multinominal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_opencl_sgd_Multinominal
 * Method:    computeDotProducts
 * Signature: (Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;IIIIILorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_sgd_Multinominal_computeDotProducts__Lorg_viennacl_binding_Buffer_2Lorg_viennacl_binding_Buffer_2Lorg_viennacl_binding_Buffer_2Lorg_viennacl_binding_Buffer_2IIIIILorg_viennacl_binding_Buffer_2Lorg_viennacl_binding_Buffer_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint, jobject, jobject);

/*
 * Class:     org_moa_opencl_sgd_Multinominal
 * Method:    computeDotProducts
 * Signature: (Lorg/viennacl/binding/Buffer;IIILorg/viennacl/binding/Buffer;Lorg/viennacl/binding/Buffer;)V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_sgd_Multinominal_computeDotProducts__Lorg_viennacl_binding_Buffer_2IIILorg_viennacl_binding_Buffer_2Lorg_viennacl_binding_Buffer_2
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
