/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_opencl_sgd_SharedSemaphores */

#ifndef _Included_org_moa_opencl_sgd_SharedSemaphores
#define _Included_org_moa_opencl_sgd_SharedSemaphores
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_opencl_sgd_SharedSemaphores
 * Method:    nativeSet
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_moa_opencl_sgd_SharedSemaphores_nativeSet
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_moa_opencl_sgd_SharedSemaphores
 * Method:    nativeGet
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_moa_opencl_sgd_SharedSemaphores_nativeGet
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
