/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_viennacl_binding_Vector */

#ifndef _Included_org_viennacl_binding_Vector
#define _Included_org_viennacl_binding_Vector
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
